sudo: false
language: node_js
node_js:
  - stable
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1fc517ea8a90c990b085
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
script:
  - npm run test
before_install:
  - pip install --user codecov
after_success:
  - npm run test:coveralls
  - codecov --file coverage/lcov.info --disable search